export type SellerStatus = "pending" | "approved" | "rejected";

export type Seller = {
  id: string;
  fullName: string;
  email: string;
  phone: string;
  shopName: string;
  category: string;
  status: SellerStatus;
  joinedAt: string;
  location: string;
  revenue: number;
  orders: number;
  products: number;
  kycVerified: boolean;
};

export const sellers: Seller[] = [
  {
    id: "sel-101",
    fullName: "Aisha Khan",
    email: "aisha@veloura.home",
    phone: "+971 55 111 2233",
    shopName: "Veloura Home",
    category: "Home & Living",
    status: "approved",
    joinedAt: "2024-01-18",
    location: "Dubai, UAE",
    revenue: 48250,
    orders: 317,
    products: 44,
    kycVerified: true,
  },
  {
    id: "sel-102",
    fullName: "Rami Haddad",
    email: "rami@lumaelec.com",
    phone: "+966 50 900 1188",
    shopName: "Luma Elec",
    category: "Electronics",
    status: "approved",
    joinedAt: "2024-02-08",
    location: "Riyadh, KSA",
    revenue: 64200,
    orders: 432,
    products: 58,
    kycVerified: true,
  },
  {
    id: "sel-103",
    fullName: "Junaid Patel",
    email: "junaid@oakjewels.co",
    phone: "+44 7700 900123",
    shopName: "Oak Jewels",
    category: "Jewelry",
    status: "pending",
    joinedAt: "2025-04-02",
    location: "London, UK",
    revenue: 12800,
    orders: 41,
    products: 24,
    kycVerified: false,
  },
  {
    id: "sel-104",
    fullName: "Mina Hassan",
    email: "mina@petalora.ae",
    phone: "+971 52 222 7788",
    shopName: "Petalora",
    category: "Beauty",
    status: "approved",
    joinedAt: "2023-12-12",
    location: "Abu Dhabi, UAE",
    revenue: 35550,
    orders: 248,
    products: 36,
    kycVerified: true,
  },
  {
    id: "sel-105",
    fullName: "Leo Martin",
    email: "leo@stridegear.com",
    phone: "+1 415 300 9390",
    shopName: "Stride Gear",
    category: "Sports",
    status: "approved",
    joinedAt: "2024-03-20",
    location: "San Francisco, US",
    revenue: 51900,
    orders: 296,
    products: 41,
    kycVerified: true,
  },
  {
    id: "sel-106",
    fullName: "Nadia Al-Sayed",
    email: "nadia@duneandco.com",
    phone: "+966 55 210 4021",
    shopName: "Dune & Co.",
    category: "Fashion",
    status: "rejected",
    joinedAt: "2025-06-15",
    location: "Jeddah, KSA",
    revenue: 0,
    orders: 0,
    products: 0,
    kycVerified: false,
  },
  {
    id: "sel-107",
    fullName: "Omar Farouk",
    email: "omar@northpeak.pk",
    phone: "+92 300 642 4400",
    shopName: "North Peak",
    category: "Outdoor",
    status: "approved",
    joinedAt: "2024-01-30",
    location: "Karachi, Pakistan",
    revenue: 40500,
    orders: 270,
    products: 33,
    kycVerified: true,
  },
  {
    id: "sel-108",
    fullName: "Sara Ibrahim",
    email: "sara@kinetik.store",
    phone: "+971 50 312 9988",
    shopName: "Kinetik Store",
    category: "Fitness",
    status: "pending",
    joinedAt: "2025-07-11",
    location: "Sharjah, UAE",
    revenue: 9300,
    orders: 22,
    products: 18,
    kycVerified: false,
  },
  {
    id: "sel-109",
    fullName: "Daniel Brooks",
    email: "daniel@bloomcraft.io",
    phone: "+1 646 874 1907",
    shopName: "Bloomcraft",
    category: "Home & Living",
    status: "approved",
    joinedAt: "2024-02-25",
    location: "New York, US",
    revenue: 61040,
    orders: 381,
    products: 52,
    kycVerified: true,
  },
  {
    id: "sel-110",
    fullName: "Huda Nasser",
    email: "huda@vantaessentials.com",
    phone: "+966 54 444 1670",
    shopName: "Vanta Essentials",
    category: "Wellness",
    status: "pending",
    joinedAt: "2025-05-28",
    location: "Doha, Qatar",
    revenue: 4700,
    orders: 8,
    products: 12,
    kycVerified: false,
  },
  {
    id: "sel-111",
    fullName: "Khalid Rahman",
    email: "khalid@vividlab.shop",
    phone: "+971 56 880 3311",
    shopName: "Vivid Lab",
    category: "Tech Accessories",
    status: "approved",
    joinedAt: "2024-06-09",
    location: "Muscat, Oman",
    revenue: 28360,
    orders: 187,
    products: 31,
    kycVerified: true,
  },
  {
    id: "sel-112",
    fullName: "Tania Ortiz",
    email: "tania@meridianwear.com",
    phone: "+34 678 889 241",
    shopName: "Meridian Wear",
    category: "Fashion",
    status: "approved",
    joinedAt: "2023-11-05",
    location: "Barcelona, Spain",
    revenue: 73890,
    orders: 512,
    products: 63,
    kycVerified: true,
  },
];

export const pendingSellerApprovals = sellers.filter((seller) => seller.status === "pending");
