-- =====================================================================================================
-- WayFair sample products (63 products, 7 categories) - generated by prepare-seed.mjs
--
-- Run ONCE against the live database. Safe to re-run: products are matched by SKU (WF-XX-NNN) and skipped when
-- they already exist; categories are matched by name.
--
-- Photos are NOT stored in the database - each ProductImages row points at /uploads/product-images/<file>, and the
-- files themselves live in WAYFEIR.Api/wwwroot/uploads/product-images/ (published with the backend).
-- Prices: SupplierCost = base price, SellingPrice = seller price = base + 23%.
-- =====================================================================================================
SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRANSACTION;

DECLARE @now DATETIME2 = SYSUTCDATETIME();

-- 1) Categories (reuse by name; a soft-deleted one with the same name is switched back on).
DECLARE @categories TABLE (Name NVARCHAR(150) PRIMARY KEY);
INSERT INTO @categories (Name) VALUES
    (N'Electronics'),
    (N'Fashion'),
    (N'Bags & Accessories'),
    (N'Beauty & Health'),
    (N'Home & Living'),
    (N'Groceries'),
    (N'Sports & Outdoors');

UPDATE c SET c.ActiveFlag = 1, c.UpdatedAtUtc = @now
FROM Categories c JOIN @categories x ON x.Name = c.Name
WHERE c.ActiveFlag = 0;

INSERT INTO Categories (Id, Name, ActiveFlag, CreatedAtUtc)
SELECT NEWID(), x.Name, 1, @now
FROM @categories x
WHERE NOT EXISTS (SELECT 1 FROM Categories c WHERE c.Name = x.Name);

-- 2) The products to add.
DECLARE @seed TABLE (
    Sku         NVARCHAR(64)   NOT NULL PRIMARY KEY,
    Name        NVARCHAR(200)  NOT NULL,
    Category    NVARCHAR(150)  NOT NULL,
    Description NVARCHAR(MAX)  NULL,
    BasePrice   DECIMAL(18, 2) NOT NULL,
    SellerPrice DECIMAL(18, 2) NOT NULL,
    FileUrl     NVARCHAR(MAX)  NOT NULL
);

INSERT INTO @seed (Sku, Name, Category, Description, BasePrice, SellerPrice, FileUrl) VALUES
    (N'WF-EL-001', N'Apple MacBook Pro 14 Inch Space Grey', N'Electronics', N'The MacBook Pro 14 Inch in Space Grey is a powerful and sleek laptop, featuring Apple''s M1 Pro chip for exceptional performance and a stunning Retina display.', 1999.99, 2459.99, N'/uploads/product-images/wf-el-001_apple-macbook-pro-14-inch-space-grey.webp'),
    (N'WF-EL-002', N'Asus Zenbook Pro Dual Screen Laptop', N'Electronics', N'The Asus Zenbook Pro Dual Screen Laptop is a high-performance device with dual screens, providing productivity and versatility for creative professionals.', 1799.99, 2213.99, N'/uploads/product-images/wf-el-002_asus-zenbook-pro-dual-screen-laptop.webp'),
    (N'WF-EL-003', N'Huawei Matebook X Pro', N'Electronics', N'The Huawei Matebook X Pro is a slim and stylish laptop with a high-resolution touchscreen display, offering a premium experience for users on the go.', 1399.99, 1721.99, N'/uploads/product-images/wf-el-003_huawei-matebook-x-pro.webp'),
    (N'WF-EL-004', N'Lenovo Yoga 920', N'Electronics', N'The Lenovo Yoga 920 is a 2-in-1 convertible laptop with a flexible hinge, allowing you to use it as a laptop or tablet, offering versatility and portability.', 1099.99, 1352.99, N'/uploads/product-images/wf-el-004_lenovo-yoga-920.webp'),
    (N'WF-EL-005', N'New DELL XPS 13 9300 Laptop', N'Electronics', N'The New DELL XPS 13 9300 Laptop is a compact and powerful device, featuring a virtually borderless InfinityEdge display and high-end performance for various tasks.', 1499.99, 1844.99, N'/uploads/product-images/wf-el-005_new-dell-xps-13-9300-laptop.webp'),
    (N'WF-EL-006', N'iPad Mini 2021 Starlight', N'Electronics', N'The iPad Mini 2021 in Starlight is a compact and powerful tablet from Apple. Featuring a stunning Retina display, powerful A-series chip, and a sleek design, it offers a premium tablet experience.', 499.99, 614.99, N'/uploads/product-images/wf-el-006_ipad-mini-2021-starlight.webp'),
    (N'WF-EL-007', N'Samsung Galaxy Tab S8 Plus Grey', N'Electronics', N'The Samsung Galaxy Tab S8 Plus in Grey is a high-performance Android tablet by Samsung. With a large AMOLED display, powerful processor, and S Pen support, it''s ideal for productivity and entertainment.', 599.99, 737.99, N'/uploads/product-images/wf-el-007_samsung-galaxy-tab-s8-plus-grey.webp'),
    (N'WF-EL-008', N'iPhone 13 Pro', N'Electronics', N'The iPhone 13 Pro is a cutting-edge smartphone with a powerful camera system, high-performance chip, and stunning display. It offers advanced features for users who demand top-notch technology.', 1099.99, 1352.99, N'/uploads/product-images/wf-el-008_iphone-13-pro.webp'),
    (N'WF-EL-009', N'Oppo A57', N'Electronics', N'The Oppo A57 is a mid-range smartphone known for its sleek design and capable features. It offers a balance of performance and affordability, making it a popular choice.', 249.99, 307.49, N'/uploads/product-images/wf-el-009_oppo-a57.webp'),
    (N'WF-FA-001', N'Blue & Black Check Shirt', N'Fashion', N'The Blue & Black Check Shirt is a stylish and comfortable men''s shirt featuring a classic check pattern. Made from high-quality fabric, it''s suitable for both casual and semi-formal occasions.', 29.99, 36.89, N'/uploads/product-images/wf-fa-001_blue-black-check-shirt.webp'),
    (N'WF-FA-002', N'Man Plaid Shirt', N'Fashion', N'The Man Plaid Shirt is a timeless and versatile men''s shirt with a classic plaid pattern. Its comfortable fit and casual style make it a wardrobe essential for various occasions.', 34.99, 43.04, N'/uploads/product-images/wf-fa-002_man-plaid-shirt.webp'),
    (N'WF-FA-003', N'Gigabyte Aorus Men Tshirt', N'Fashion', N'The Gigabyte Aorus Men Tshirt is a cool and casual shirt for gaming enthusiasts. With the Aorus logo and sleek design, it''s perfect for expressing your gaming style.', 24.99, 30.74, N'/uploads/product-images/wf-fa-003_gigabyte-aorus-men-tshirt.webp'),
    (N'WF-FA-004', N'Nike Air Jordan 1 Red And Black', N'Fashion', N'The Nike Air Jordan 1 in Red and Black is an iconic basketball sneaker known for its stylish design and high-performance features, making it a favorite among sneaker enthusiasts and athletes.', 149.99, 184.49, N'/uploads/product-images/wf-fa-004_nike-air-jordan-1-red-and-black.webp'),
    (N'WF-FA-005', N'Puma Future Rider Trainers', N'Fashion', N'The Puma Future Rider Trainers offer a blend of retro style and modern comfort. Perfect for casual wear, these trainers provide a fashionable and comfortable option for everyday use.', 89.99, 110.69, N'/uploads/product-images/wf-fa-005_puma-future-rider-trainers.webp'),
    (N'WF-FA-006', N'Nike Baseball Cleats', N'Fashion', N'Nike Baseball Cleats are designed for maximum traction and performance on the baseball field. They provide stability and support for players during games and practices.', 79.99, 98.39, N'/uploads/product-images/wf-fa-006_nike-baseball-cleats.webp'),
    (N'WF-FA-007', N'Black Women''s Gown', N'Fashion', N'The Black Women''s Gown is an elegant and timeless evening gown. With a sleek black design, it''s perfect for formal events and special occasions, exuding sophistication and style.', 129.99, 159.89, N'/uploads/product-images/wf-fa-007_black-women-s-gown.webp'),
    (N'WF-FA-008', N'Corset Leather With Skirt', N'Fashion', N'The Corset Leather With Skirt is a bold and edgy ensemble that combines a stylish corset with a matching skirt. Ideal for fashion-forward individuals, it makes a statement at any event.', 89.99, 110.69, N'/uploads/product-images/wf-fa-008_corset-leather-with-skirt.webp'),
    (N'WF-FA-009', N'Girl Summer Dress', N'Fashion', N'The Girl Summer Dress is a cute and breezy dress designed for warm weather. With playful patterns and lightweight fabric, it''s perfect for keeping cool and stylish during the summer.', 19.99, 24.59, N'/uploads/product-images/wf-fa-009_girl-summer-dress.webp'),
    (N'WF-BA-001', N'Blue Women''s Handbag', N'Bags & Accessories', N'The Blue Women''s Handbag is a stylish and spacious accessory for everyday use. With a vibrant blue color and multiple compartments, it combines fashion and functionality.', 49.99, 61.49, N'/uploads/product-images/wf-ba-001_blue-women-s-handbag.webp'),
    (N'WF-BA-002', N'Heshe Women''s Leather Bag', N'Bags & Accessories', N'The Heshe Women''s Leather Bag is a luxurious and high-quality leather bag for the sophisticated woman. With a timeless design and durable craftsmanship, it''s a versatile accessory.', 129.99, 159.89, N'/uploads/product-images/wf-ba-002_heshe-women-s-leather-bag.webp'),
    (N'WF-BA-003', N'Prada Women Bag', N'Bags & Accessories', N'The Prada Women Bag is an iconic designer bag that exudes elegance and luxury. Crafted with precision and featuring the Prada logo, it''s a statement piece for fashion enthusiasts.', 599.99, 737.99, N'/uploads/product-images/wf-ba-003_prada-women-bag.webp'),
    (N'WF-BA-004', N'White Faux Leather Backpack', N'Bags & Accessories', N'The White Faux Leather Backpack is a trendy and practical backpack for the modern woman. With a sleek white design and ample storage space, it''s perfect for both casual and on-the-go styles.', 39.99, 49.19, N'/uploads/product-images/wf-ba-004_white-faux-leather-backpack.webp'),
    (N'WF-BA-005', N'Black Sun Glasses', N'Bags & Accessories', N'The Black Sun Glasses are a classic and stylish choice, featuring a sleek black frame and tinted lenses. They provide both UV protection and a fashionable look.', 29.99, 36.89, N'/uploads/product-images/wf-ba-005_black-sun-glasses.webp'),
    (N'WF-BA-006', N'Classic Sun Glasses', N'Bags & Accessories', N'The Classic Sun Glasses offer a timeless design with a neutral frame and UV-protected lenses. These sunglasses are versatile and suitable for various occasions.', 24.99, 30.74, N'/uploads/product-images/wf-ba-006_classic-sun-glasses.webp'),
    (N'WF-BA-007', N'Green and Black Glasses', N'Bags & Accessories', N'The Green and Black Glasses feature a bold combination of green and black colors, adding a touch of vibrancy to your eyewear collection. They are both stylish and eye-catching.', 34.99, 43.04, N'/uploads/product-images/wf-ba-007_green-and-black-glasses.webp'),
    (N'WF-BA-008', N'Brown Leather Belt Watch', N'Bags & Accessories', N'The Brown Leather Belt Watch is a stylish timepiece with a classic design. Featuring a genuine leather strap and a sleek dial, it adds a touch of sophistication to your look.', 89.99, 110.69, N'/uploads/product-images/wf-ba-008_brown-leather-belt-watch.webp'),
    (N'WF-BA-009', N'Longines Master Collection', N'Bags & Accessories', N'The Longines Master Collection is an elegant and refined watch known for its precision and craftsmanship. With a timeless design, it''s a symbol of luxury and sophistication.', 1499.99, 1844.99, N'/uploads/product-images/wf-ba-009_longines-master-collection.webp'),
    (N'WF-BH-001', N'Essence Mascara Lash Princess', N'Beauty & Health', N'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.', 9.99, 12.29, N'/uploads/product-images/wf-bh-001_essence-mascara-lash-princess.webp'),
    (N'WF-BH-002', N'Eyeshadow Palette with Mirror', N'Beauty & Health', N'The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it''s convenient for on-the-go makeup application.', 19.99, 24.59, N'/uploads/product-images/wf-bh-002_eyeshadow-palette-with-mirror.webp'),
    (N'WF-BH-003', N'Powder Canister', N'Beauty & Health', N'The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.', 14.99, 18.44, N'/uploads/product-images/wf-bh-003_powder-canister.webp'),
    (N'WF-BH-004', N'Red Lipstick', N'Beauty & Health', N'The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.', 12.99, 15.98, N'/uploads/product-images/wf-bh-004_red-lipstick.webp'),
    (N'WF-BH-005', N'Red Nail Polish', N'Beauty & Health', N'The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home.', 8.99, 11.06, N'/uploads/product-images/wf-bh-005_red-nail-polish.webp'),
    (N'WF-BH-006', N'Calvin Klein CK One', N'Beauty & Health', N'CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It''s a versatile fragrance suitable for everyday wear.', 49.99, 61.49, N'/uploads/product-images/wf-bh-006_calvin-klein-ck-one.webp'),
    (N'WF-BH-007', N'Chanel Coco Noir Eau De', N'Beauty & Health', N'Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood. Perfect for evening occasions.', 129.99, 159.89, N'/uploads/product-images/wf-bh-007_chanel-coco-noir-eau-de.webp'),
    (N'WF-BH-008', N'Dior J''adore', N'Beauty & Health', N'J''adore by Dior is a luxurious and floral fragrance, known for its blend of ylang-ylang, rose, and jasmine. It embodies femininity and sophistication.', 89.99, 110.69, N'/uploads/product-images/wf-bh-008_dior-j-adore.webp'),
    (N'WF-BH-009', N'Gucci Bloom Eau de', N'Beauty & Health', N'Gucci Bloom by Gucci is a floral and captivating fragrance, with notes of tuberose, jasmine, and Rangoon creeper. It''s a modern and romantic scent.', 79.99, 98.39, N'/uploads/product-images/wf-bh-009_gucci-bloom-eau-de.webp'),
    (N'WF-HL-001', N'Annibale Colombo Bed', N'Home & Living', N'The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom.', 1899.99, 2336.99, N'/uploads/product-images/wf-hl-001_annibale-colombo-bed.webp'),
    (N'WF-HL-002', N'Annibale Colombo Sofa', N'Home & Living', N'The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room.', 2499.99, 3074.99, N'/uploads/product-images/wf-hl-002_annibale-colombo-sofa.webp'),
    (N'WF-HL-003', N'Bedside Table African Cherry', N'Home & Living', N'The Bedside Table in African Cherry is a stylish and functional addition to your bedroom, providing convenient storage space and a touch of elegance.', 299.99, 368.99, N'/uploads/product-images/wf-hl-003_bedside-table-african-cherry.webp'),
    (N'WF-HL-004', N'Knoll Saarinen Executive Conference Chair', N'Home & Living', N'The Knoll Saarinen Executive Conference Chair is a modern and ergonomic chair, perfect for your office or conference room with its timeless design.', 499.99, 614.99, N'/uploads/product-images/wf-hl-004_knoll-saarinen-executive-conference-chair.webp'),
    (N'WF-HL-005', N'Wooden Bathroom Sink With Mirror', N'Home & Living', N'The Wooden Bathroom Sink with Mirror is a unique and stylish addition to your bathroom, featuring a wooden sink countertop and a matching mirror.', 799.99, 983.99, N'/uploads/product-images/wf-hl-005_wooden-bathroom-sink-with-mirror.webp'),
    (N'WF-HL-006', N'Decoration Swing', N'Home & Living', N'The Decoration Swing is a charming addition to your home decor. Crafted with intricate details, it adds a touch of elegance and whimsy to any room.', 59.99, 73.79, N'/uploads/product-images/wf-hl-006_decoration-swing.webp'),
    (N'WF-HL-007', N'Family Tree Photo Frame', N'Home & Living', N'The Family Tree Photo Frame is a sentimental and stylish way to display your cherished family memories. With multiple photo slots, it tells the story of your loved ones.', 29.99, 36.89, N'/uploads/product-images/wf-hl-007_family-tree-photo-frame.webp'),
    (N'WF-HL-008', N'House Showpiece Plant', N'Home & Living', N'The House Showpiece Plant is an artificial plant that brings a touch of nature to your home without the need for maintenance. It adds greenery and style to any space.', 39.99, 49.19, N'/uploads/product-images/wf-hl-008_house-showpiece-plant.webp'),
    (N'WF-HL-009', N'Plant Pot', N'Home & Living', N'The Plant Pot is a stylish container for your favorite plants. With a sleek design, it complements your indoor or outdoor garden, adding a modern touch to your plant display.', 14.99, 18.44, N'/uploads/product-images/wf-hl-009_plant-pot.webp'),
    (N'WF-GR-001', N'Apple', N'Groceries', N'Fresh and crisp apples, perfect for snacking or incorporating into various recipes.', 1.99, 2.45, N'/uploads/product-images/wf-gr-001_apple.webp'),
    (N'WF-GR-002', N'Beef Steak', N'Groceries', N'High-quality beef steak, great for grilling or cooking to your preferred level of doneness.', 12.99, 15.98, N'/uploads/product-images/wf-gr-002_beef-steak.webp'),
    (N'WF-GR-003', N'Eggs', N'Groceries', N'Fresh eggs, a versatile ingredient for baking, cooking, or breakfast.', 2.99, 3.68, N'/uploads/product-images/wf-gr-003_eggs.webp'),
    (N'WF-GR-004', N'Honey Jar', N'Groceries', N'Pure and natural honey in a convenient jar, perfect for sweetening beverages or drizzling over food.', 6.99, 8.60, N'/uploads/product-images/wf-gr-004_honey-jar.webp'),
    (N'WF-GR-005', N'Milk', N'Groceries', N'Fresh and nutritious milk, a staple for various recipes and daily consumption.', 3.49, 4.29, N'/uploads/product-images/wf-gr-005_milk.webp'),
    (N'WF-GR-006', N'Nescafe Coffee', N'Groceries', N'Quality coffee from Nescafe, available in various blends for a rich and satisfying cup.', 7.99, 9.83, N'/uploads/product-images/wf-gr-006_nescafe-coffee.webp'),
    (N'WF-GR-007', N'Rice', N'Groceries', N'High-quality rice, a staple for various cuisines and a versatile base for many dishes.', 5.99, 7.37, N'/uploads/product-images/wf-gr-007_rice.webp'),
    (N'WF-GR-008', N'Strawberry', N'Groceries', N'Sweet and succulent strawberries, great for snacking, desserts, or blending into smoothies.', 3.99, 4.91, N'/uploads/product-images/wf-gr-008_strawberry.webp'),
    (N'WF-GR-009', N'Cooking Oil', N'Groceries', N'Versatile cooking oil suitable for frying, sautéing, and various culinary applications.', 4.99, 6.14, N'/uploads/product-images/wf-gr-009_cooking-oil.webp'),
    (N'WF-SP-001', N'Football', N'Sports & Outdoors', N'The Football, also known as a soccer ball, is the standard ball used in the sport of football (soccer). It is designed for kicking and passing in the game.', 17.99, 22.13, N'/uploads/product-images/wf-sp-001_football.webp'),
    (N'WF-SP-002', N'Basketball', N'Sports & Outdoors', N'The Basketball is a standard ball used in basketball games. It is designed for dribbling, shooting, and passing in the game of basketball, suitable for both indoor and outdoor play.', 14.99, 18.44, N'/uploads/product-images/wf-sp-002_basketball.webp'),
    (N'WF-SP-003', N'Cricket Bat', N'Sports & Outdoors', N'The Cricket Bat is an essential piece of cricket equipment used by batsmen to hit the cricket ball. It is made of wood and comes in various sizes and designs.', 29.99, 36.89, N'/uploads/product-images/wf-sp-003_cricket-bat.webp'),
    (N'WF-SP-004', N'Tennis Racket', N'Sports & Outdoors', N'The Tennis Racket is an essential piece of equipment used in the sport of tennis. It features a frame with strings and a grip, allowing players to hit the tennis ball.', 49.99, 61.49, N'/uploads/product-images/wf-sp-004_tennis-racket.webp'),
    (N'WF-SP-005', N'Volleyball', N'Sports & Outdoors', N'The Volleyball is a standard ball used in the sport of volleyball. It is designed for passing, setting, and spiking over the net during volleyball matches.', 11.99, 14.75, N'/uploads/product-images/wf-sp-005_volleyball.webp'),
    (N'WF-SP-006', N'Baseball Glove', N'Sports & Outdoors', N'The Baseball Glove is a protective glove worn by baseball players. It is designed to catch and field the baseball, providing players with comfort and control during the game.', 24.99, 30.74, N'/uploads/product-images/wf-sp-006_baseball-glove.webp'),
    (N'WF-SP-007', N'Iron Golf', N'Sports & Outdoors', N'The Iron Golf is a type of golf club designed for various golf shots. It features a solid metal head and is used for approach shots, chipping, and other golfing techniques.', 49.99, 61.49, N'/uploads/product-images/wf-sp-007_iron-golf.webp'),
    (N'WF-SP-008', N'American Football', N'Sports & Outdoors', N'The American Football is a classic ball used in American football games. It is designed for throwing and catching, making it an essential piece of equipment for the sport.', 19.99, 24.59, N'/uploads/product-images/wf-sp-008_american-football.webp'),
    (N'WF-SP-009', N'Golf Ball', N'Sports & Outdoors', N'The Golf Ball is a small ball used in the sport of golf. It features dimples on its surface, providing aerodynamic lift and distance when struck by a golf club.', 9.99, 12.29, N'/uploads/product-images/wf-sp-009_golf-ball.webp');

-- 3) Products that don't exist yet (matched by SKU).
INSERT INTO Products (Id, CategoryId, Name, Sku, Description, SupplierCost, SellingPrice, StockQuantity, IsAvailable, ActiveFlag, CreatedAtUtc)
SELECT NEWID(), c.Id, s.Name, s.Sku, s.Description, s.BasePrice, s.SellerPrice, 0, 1, 1, @now
FROM @seed s
JOIN Categories c ON c.Name = s.Category
WHERE NOT EXISTS (SELECT 1 FROM Products p WHERE p.Sku = s.Sku);

DECLARE @productsAdded INT = @@ROWCOUNT;

-- 4) One photo row per seeded product (skipped if that exact photo is already linked).
INSERT INTO ProductImages (Id, ProductId, FileUrl, ActiveFlag, CreatedAtUtc)
SELECT NEWID(), p.Id, s.FileUrl, 1, @now
FROM @seed s
JOIN Products p ON p.Sku = s.Sku
WHERE NOT EXISTS (SELECT 1 FROM ProductImages i WHERE i.ProductId = p.Id AND i.FileUrl = s.FileUrl);

DECLARE @photosAdded INT = @@ROWCOUNT;

-- 5) Result.
SELECT @productsAdded AS ProductsAdded,
       63 - @productsAdded AS AlreadyExisted,
       @photosAdded AS PhotosLinked;

SELECT c.Name AS Category, COUNT(*) AS Products
FROM Products p JOIN Categories c ON c.Id = p.CategoryId
WHERE p.Sku LIKE 'WF-%'
GROUP BY c.Name ORDER BY c.Name;

COMMIT TRANSACTION;

-- -----------------------------------------------------------------------------------------------------
-- To remove these sample products again (only if no order uses them), run:
--   DELETE FROM ProductImages WHERE ProductId IN (SELECT Id FROM Products WHERE Sku LIKE 'WF-%');
--   DELETE FROM Products WHERE Sku LIKE 'WF-%';
-- -----------------------------------------------------------------------------------------------------
